name: After Snapshots

on:
  workflow_run:
    workflows: [ Snapshots ]
    types:
      - completed

permissions: read-all

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed successfully! ${{ toJson(github.event.workflow_run) }}'
